// src/core/models/index.ts
// Non-DB interfaces, enums, and constants.
// DB model types are generated by Prisma — import from '@prisma/client' or 'src/generated/prisma'.
import { Request } from 'express';

// Re-export Prisma-generated types for convenience
export type {
    Account,
    AccountCredential,
    EmailVerification,
    PhoneVerification,
    Tenant,
    TenantMembership,
    OAuthClient,
    OAuthAuthorizationCode,
    OAuthRefreshToken,
} from '../../generated/prisma/client';

/**
 * User role enumeration
 */
export enum UserRole {
    USER = 1,
    MODERATOR = 2,
    ADMIN = 3,
    SUPER_ADMIN = 4,
    OWNER = 5,
}

/**
 * Map role numbers to role names
 */
export const RoleName = {
    [UserRole.USER]: 'User',
    [UserRole.MODERATOR]: 'Moderator',
    [UserRole.ADMIN]: 'Admin',
    [UserRole.SUPER_ADMIN]: 'SuperAdmin',
    [UserRole.OWNER]: 'Owner',
} as const;

/**
 * JWT token payload structure
 */
export interface JwtClaims {
    id: number;
    name: string;
    role: UserRole;
    iat?: number;
    exp?: number;
}

/**
 * Express Request with JWT claims and target user info
 */
export interface JwtRequest extends Request {
    claims?: JwtClaims;
    targetUserRole?: UserRole; // Used by role hierarchy middleware
}

/**
 * Password reset token payload
 */
export interface PasswordResetToken {
    id: number;
    email: string;
    type: 'password_reset';
    iat?: number;
    exp?: number;
}

/**
 * JWT Configuration Constants
 */
export const JWT_EXPIRY = '14d'; // Access token expiry
export const JWT_RESET_EXPIRY = '1h'; // Password reset token expiry

// Email-to-SMS gateway mappings
export const SMS_GATEWAYS: { [key: string]: string } = {
    // US Carriers
    att: '@txt.att.net',
    tmobile: '@tmomail.net',
    verizon: '@vtext.com',
    sprint: '@messaging.sprintpcs.com',
    boost: '@sms.myboostmobile.com',
    cricket: '@sms.cricketwireless.net',
    metro: '@mymetropcs.com',
    tracfone: '@mmst5.tracfone.com',
    uscellular: '@email.uscc.net',
    virgin: '@vmobl.com',

    // Canadian Carriers
    telus: '@msg.telus.com',
    bell: '@txt.bellmobility.ca',
    rogers: '@pcs.rogers.com',
    fido: '@fido.ca',
    koodo: '@msg.koodomobile.com',

    // For testing/development
    test: '@example.com',
    mock: '@mock.local',
};
